### ISSUE TITLE
Please fix labels page

### ISSUE THREAD

**Issue by bricel** [Gizra/TheGizraWay#5]
Remove the one with red dot + define standard colors
![issue_queue_ _the_gizra_way](https://cloud.githubusercontent.com/assets/165644/8454818/d7ee1222-2008-11e5-9ea1-ab79ce0a4596.png)

**Comment by ordavidil** [comment]
@bricel 
Here's the gist for the [Gizra Default Labels](https://gist.github.com/ordavidil/261fee4f35cc41e8c5fb) script file.

**Comment by ordavidil** [comment]
![selection_344](https://cloud.githubusercontent.com/assets/5985683/8766694/f8fc48c6-2e4a-11e5-86ed-d3ace54e11c5.png)
